### ISSUE TITLE
Migration of an embedded neo4j database fails with "Invalid JDBC URI" error

### ISSUE THREAD

**Issue by geld0r** [fbiville/liquigraph#134]
As mentioned in #107 it should be possible to migrate an embedded neo4j database.

According to that I have configured:
`Configuration configuration = new ConfigurationBuilder()
					.withMasterChangelogLocation("changelog.xml")
					.withUri("jdbc:neo4j:mem:neo4j")
					.withRunMode()
					.build();`

where the name of my neo4j db is "neo4j" (to be honest I am not sure what the name of the instance is - this is the name of the folder it resides in).

Anyways, configuring this fails with a validation error:

> java.lang.RuntimeException: 
	 - Invalid JDBC URI. Supported configurations:
	 - jdbc:neo4j:http(s)://<host>:<port>/
	 - jdbc:neo4j:bolt://<host>:<port>/
Given: jdbc:neo4j:mem:neo4j

Was support for migrating an embedded database dropped?
I am using version 3.0.0

**Comment by fbiville** [comment]
Hi, for embedded support, you should use the 2.x version branch.
Feature-wise, it is the same.

The driver used under the hood is different in 3.x and does not support embedded databases yet.

**Comment by fbiville** [comment]
I think so. I'll check and reproduce the problem, but I wouldn't be surprised if the legacy driver is not compatible with Neo4j 3.

If that's the case, then the only solution is to wait for the embedded support in the new JDBC driver. That's planned but not done yet.

**Comment by fbiville** [comment]
So, I reproduced your setup and tried both embedded and in-memory (with the test JARs) Neo4j 3.x with Liquigraph 2.0.0 and it fails because of incompatible API changes between Neo4j 2.x and Neo4j 3.x.

The above error occurs because you have not included the test JARs to instanciate an in-memory database (indeed, the in-memory version of Neo4j is intended for tests only).

**Comment by fbiville** [comment]
For now, I am afraid you are out of luck: if you use Neo4j 3.x, you need to run Liquigraph 3.0.0. 

The underlying driver makes it so only BOLT and HTTP connections are supported (this will change in the future but this is not available now). 

Otherwise, downgrade to Neo4j 2.3.x and run Liquigraph 2.0.0 (in-memory, file, HTTP).

**Comment by fbiville** [comment]
For more reference, you can follow the gist I created (sorry, for the weird filenames, but Gist won't let me order the files the way I want or put "/" in the names) : https://gist.github.com/fbiville/7d2cddac40557c33b8b0fbae4400af1c

**Comment by geld0r** [comment]
Thank you for your quick and thorough investigation!
I can't downgrade to Neo4j 2.x anymore, so I'll postpone using Liquigraph until embedded Neo4j is supported again or I've moved to any of the other protocols. I'll definitely keep an eye on Liquigraph though, as this seems like the perfect solution for doing migrations.
