### ISSUE TITLE
[Core] Avoid concurrent executions

### ISSUE THREAD

**Issue by fbiville** [fbiville/liquigraph#23]

**Comment by fbiville** [comment]
The idea would be to implement a mutex based on the presence of a (unique) node labeled `:__LIQUIGRAPH_LOCK`.
The node removal could be register as a JVM shutdown hook.
All reads/writes must be based on mutual exclusion.

**Comment by sim51** [comment]
Be a little patient, I'm on it. A first version will be pushed on  the branch issue_23

**Comment by fbiville** [comment]
I know, I know, I'm just throwing out some ideas :)

**Comment by mbyrne00** [comment]
@fbiville mentioned that there is a potential for a race condition with the current solution as mentioned here: https://groups.google.com/forum/?hl=en-GB#!topic/neo4j/28t4xOlhGLg

I’m not sure there is any need for a pessimistic lock via “SELECT FOR UPDATE”. A simpler solution would be to create a unique constraint in the db on `:__LiquigraphLock(lock)` (or any other arbitrary property) and when you create the node always set it to `true` or use some other constant value in the node. 

On startup you can check if a constraint exists with that label and if not try to create one. If you get race conditions creating the constraint you could wait for a random interval and check again. This would be a once-off operation and once this is out of the way you can be guaranteed your lock will only be created once - or an error is returned.

Hope that helps - in the mean time the work done to date would still be beneficial to merge.

**Comment by fbiville** [comment]
OK, I'll commit the unicity constraint. It won't *directly* help with the race condition (it may still happen unless using pessimistic locking) but the conflicting thread, as @mbyrne00 says, will at least fail to create the lock and won't execute further. This is still an improvement compared with the current version.

I think this is an acceptable compromise for now. WDYT?

**Comment by mbyrne00** [comment]
@fbville - our team need to write some custom rollforward mechanisms for our immediate urgent requirements right now, so I won't be able to use your product, but after looking through the code here's some of my feedback. I was going to work on a pull request on a local fork to give this feedback in code, but I've been pulled off this sorry. Some of my comments may be due to lack of understanding so please feel free to disregard.

Unique constraint can always be guaranteed to prevent race conditions. You need to create the constraint _before_ you try to get the lock since neo is forgiving if the constraint is already there. Instead of trying to retrieve the lock and then create if it doesn't exist, the while loop can try to create the lock _directly_ and if you get a constraint violation then treat that the same as the lock being not available. Doing this in one step avoids race conditions. You can detect constraint violation by checking if the SqlException.getCause().getMessage() contains "Neo.ClientError.Schema.ConstraintViolation" (with null checks of course). Neo has an enum for error codes that you can use and the String representation of this error code is `org.neo4j.kernel.api.exceptions.Status.Schema.ConstraintViolation.code().serialize()`.

Your JVM shutdown hook that deletes the lock node (a failsafe mechanism) should probably have a condition "WHERE ip={ip}" so you don't accidentally delete another locked process's lock node, since you are already delete it in the `finally` if the JVM doesn't crash beforehand.

When I changed `EnbeddedGraphDatabaseRule` to point to "jdbc:neo4j://localhost:7474/" and ran a few tests I got a bunch of `ClassCastExceptions` because of this line in `LockManager` ... `Node node = (Node) rs.getObject("lock");` since I believe this will  only work when it's pointed to the local neo4j. When pointing to a remote one the node is a `HashMap` so this can be resolved by returning the properties directly in the query. Not sure if you have a build dedicated to trying this on neo server setup.

The concurrency stuff in `LockManager` can hang forever when a lock node has been created in another JVM since there is no signal sent to it. I noticed this when I ran neo as a server and manually created a lock node in my web console. The test hung and `LockManager` didn't seem to retry after I deleted the node through the web console.

Another comment ... this may just be me not understanding properly and it's not related to this issue ... in `ChangelogGraphReader` I see a bunch of `commit()` statements but no `rollback()` if there's an error. It also seems to use a single transaction? (I haven't used JDBC API directly for some years now). I believe flyway will open a transaction for every changelog and either commit/rollback that transaction based on success/error. Not sure if that's happening here.

Anyway, great work you've done with this tool and thanks for putting it on github to share!

**Comment by fbiville** [comment]
@mbyrne00 thanks for this detailed feedback. While I need some time to process it all, here come a few answers:

 1. changing the while loop: you're probably right, it looks more cumbersome but also more reliable, so I'll give it a try.
 1. `LockManager` hanging: I'll write some more tests to cover the case
 1. `ClassCastException`: sounds definitely familiar :/
 1. no `rollback`: as far as I remember, a closed connection that hasn't been committed will end up being rolled back. I'll check again though ;)
 1. single transaction: nope, that's not the case. We worked on that a bit earlier to allow migration that modify the schema. If there were only a single transaction, such migrations would fail as there would be a mix of schema changes (defined by 1-n migration(s)) and data changes (inserts into the history graph).

Finally, I'm curious about the "some custom rollforward mechanisms" you mention.
What do you need to do?

**Comment by mbyrne00** [comment]
For our setup I think we may need the ability to have at least some changesets defined in a Java class like the Flyway model allows. Some of the properties we store are SHA encoded for example and some migrations could potentially need more logic than Cypher. We can also use some ideas of allowing Spring-managed beans to be accessed at the same time. For now we will have a dependency on some internal code to run the changesets (we don't use JDBC driver, but a wrapper around the REST API directly - gives us better access to graph responses, index querying, etc) so our first implementation will be custom internal since we have an immediate need for something, but we'd also like to see if we can open it up in the future. There are some neat ideas from your source too that have really helped shape our plans. 

I thought I must have been wrong about the transactions and your points 4 and 5 make sense - glad to hear. Thanks again and will check back in on the project. Cheers.

**Comment by fbiville** [comment]
@mbyrne00 you can always depend on `liquigraph-core` and instantiate the Java classes yourself.
However, for now, you can only define your migration with Cypher queries.

**Comment by fbiville** [comment]
Sorry guys for the loooooooong silence here.
Work has been crazily busy in the last months and I finally get some time to work on the issue and make sure the so-long overdue RC3 appear.

**Comment by fbiville** [comment]
I just spend some time in setting up automated testing against a remote instance with Docker and Travis.
I can at least reproduce automatically the issues that have been mentioned in this thread.

Hopefully will fix everything in the following days!!

**Comment by heroicefforts** [comment]
What's the status on #23?  Is there a release forthcoming?  Is the 23 branch stable?

**Comment by fbiville** [comment]
Still ongoing, trying to automate tests on remote instances with Docker, I'm struggling a bit with my home setup.

**Comment by fbiville** [comment]
@heroicefforts @mbyrne00 I know this is late, but I'm gonna take a rather simple "fail-fast" approach. When acquiring a connection, Liquigraph will create a unique node, and crash if it cannot (with an explicit error message).

**Comment by fbiville** [comment]
Here comes the simplified approach: https://github.com/fbiville/liquigraph/pull/49. Needs a bit more testing, but this should be good enough fail-fast approach.

**Comment by fbiville** [comment]
@heroicefforts @mbyrne00 I'm happy to tell you changes have finally been pushed to master...
I'm gonna make some more manual testing and a new release candidate will be created.

Feel free to reopen the issue if you think something is not working properly regarding the locking mechanism.
