### ISSUE TITLE
[Core] Add Tags to liquigraph

### ISSUE THREAD

**Issue by airomega** [fbiville/liquigraph#87]
It would be useful to be able to add Tags to Liquigraph. This would allow users to add versioning to their database allowing installation of specific versions and roll back to previous versions (assuming rollback is implemented) .

**Comment by fbiville** [comment]
@airomega FYI I just opened https://github.com/fbiville/liquigraph/pull/91. Unless I'm mistaken, this should be enough to fit the bill.
Feel free to review the PR :-)

**Comment by airomega** [comment]
Looks good :+1: 

It is worth while considering adding timestamps to _LiquigraphChangeset and Tag nodes to assist determining what changesets were added before a specific tag and which were added after? Maybe there's another way/mechanism this is handled already....

**Comment by fbiville** [comment]
Tag is not a node in the current impl, just an attribute of the `__LiquigraphChangelog` node.

**Comment by airomega** [comment]
Cool. My mistake looking at the neo4j guide and not paying enough attention
:)  the idea is still valid I think - it is worth adding a timestamp to the
tag and changeset in some way?

**Comment by fbiville** [comment]
Yep, I can add a `last_access` to changelog.
Changesets already have a creation timestamp, so I'm not sure we need to replicate the last access timestamp elsewhere than in the changelog node, what do you think?

**Comment by fbiville** [comment]
In the end, I added a `tag_timestamp` attribute. It matches the creation time of the tag.

**Comment by fbiville** [comment]
I'm wondering if the checksum definition should be modified...
WDYT @fpavageau?

For now, only changeset queries are included in checksum computation, but it could make sense to include pre- and post-condition as well as tags. If so, I'll open another issue and do the work there... I'm not super with the way the checksum computation is currently triggered...

**Comment by fpavageau** [comment]
Regarding #91, it implements the tag but there's no easy way to access it at the moment, except with a direct Cypher query on the `__LiquigraphChangelog` node. Should it be accessible through the API? How is it going to be used in practice?

As for what's included in the checksum, I feel like it would be more difficult to manage bugs in changesets if pre- and postconditions were included, but I'm not sure how much.

Currently, my lifecycle for changeset management looks like:
  - create the changeset which satisfies the tests locally
  - push it and deploy it to some test environment
  - realize it should not be applied to all environments indiscriminately
  - add a precondition to only migrate selected environments
  - PROFIT!!!

Of course, I'd mainly be annoyed if that changed the checksum because I'd have to use `run-on-change="true"`, and I can't because I'm running RC2 (see #58). However, it also requires including in the precondition the detection of environments where the changeset has already run but that otherwise satisfy the criteria, because you don't usually don't want to run the changeset again in that case. Most of my changesets are **not** idempotent. So now you have to make sure that your changeset can be detected, when that's actually why you use Liquigraph in the first place 😄.

So, that'd be my reason for not including preconditions in the checksum. As for postconditions, I guess they don't represent a problem, because they're already supposed to detect that a changeset has been fully applied. So if you change the postcondition, it's probably because it stopped the migration too early, in which case it would make sense to re-apply the changeset. It has the drawback of making the composition of the checksum harder to understand, though, as it becomes less regular.

I see the rationale for including the tags, but then you have the same problem as with preconditions: if you need to fix the tag, should you really re-run the migration (or be able to detect it's already been run)? You can always add a new changeset which does nothing (`RETURN false`) but has the correct tag.

**Comment by fbiville** [comment]
Good points, I agree we can keep the checksum computation to the minimum.

Regarding tags, unless @airomega sees otherwise, I just see them as a human-friendly state that could help writing some subsequent preconditions (or maybe rollback if/when we implement it). I don't think we explicitly need tags in the API.

**Comment by fbiville** [comment]
@fpavageau If we plan to have a dedicate API for reading tags:

- is retrieving the current one enough? (by current design, that's the only option)
- do we need to retrieve all tags (need to rewrite the PR to keep all tags in the DB)

**Comment by fbiville** [comment]
@fpavageau @airomega see questions above: how should the tag API behave? ;-)

**Comment by fpavageau** [comment]
I think having all the tags would be more flexible, but I'm not sure I really see the use cases anyway (Rollback? Maybe).

**Comment by fbiville** [comment]
Closing it for now. Feel free to reopen it if you have a clear idea about how this should work.
